In [13]:
import numpy as np

### Numpy Array vs. Python List

* At first glance, NumPy arrays are similar to Python lists. They both serve as containers with fast item getting and setting and somewhat slower inserts and removals of elements.

* The hands-down simplest example when NumPy arrays beat lists is arithmetic:

In [14]:
# normal python list with iteration
a = [1,2,3]

[i * 2 for i in a]

[2, 4, 6]

In [15]:
# numpy array
a = np.array([1,2,3])

a * 2

array([2, 4, 6])

In [16]:
a = [1,2,3]
b = [4,5,6]

[i+j for i, j in zip(a,b)]

[5, 7, 9]

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])

a + b

array([5, 7, 9])

#### Other than that, NumPy arrays are:

* more compact, especially when there’s more than one dimension
* faster than lists when the operation can be vectorized
* slower than lists when you append elements to the end
* usually homogeneous: can only work fast with elements of one type

In [24]:
a = np.array([1,2,3])
a.shape, a.dtype

((3,), dtype('int64'))

In [25]:
b = np.zeros(3, int)
b, b.dtype

(array([0, 0, 0]), dtype('int64'))

In [27]:
c = np.zeros_like(a)
c, c.shape, c.dtype

(array([0, 0, 0]), (3,), dtype('int64'))

Actually, all the functions that create an array filled with a constant value have a _like counterpart:

In [28]:
a = np.array([1,2,3])

In [30]:
np.zeros(3), np.zeros_like(a)

(array([0., 0., 0.]), array([0, 0, 0]))

In [31]:
np.ones(3), np.ones_like(a)

(array([1., 1., 1.]), array([1, 1, 1]))

In [33]:
np.empty(3), np.empty_like(a)

(array([1., 1., 1.]),
 array([4607182418800017408, 4607182418800017408, 4607182418800017408]))

In [35]:
np.full(3, 7), np.full_like(a, 7)

(array([7, 7, 7]), array([7, 7, 7]))

In [36]:
# np.arange(start, stop, step)
# np.linspace(start, stop, num)

np.arange(1, 6, 2), np.linspace(0, 0.5, 6)

(array([1, 3, 5]), array([0. , 0.1, 0.2, 0.3, 0.4, 0.5]))

In [42]:
a = np.arange(3)
a, a.astype(float)

(array([0, 1, 2]), array([0., 1., 2.]))

In [43]:
np.random.randint(0,10,3)

array([9, 8, 4])

In [46]:
# uniform
np.random.rand(3)

array([0.12768467, 0.86173664, 0.84132211])

In [47]:
# normal
np.random.randn(3)

array([-1.19881222, -0.29990365, -1.15556405])

In [49]:
# uniform
np.random.uniform(1, 10, 3)

array([6.53589527, 1.69955376, 4.70016616])

In [50]:
# normal
np.random.normal(5, 2, 3)

array([4.00957796, 3.0122719 , 3.89703869])